### ISSUE TITLE
Mock of New-PSDrive failing with error about dynamic parameters

### ISSUE THREAD

**Issue by kwirkykat** [pester/Pester#728]
My mock of New-PSDrive always throws an error about dynamic parameters when called with the 'FileSytem' provider and a credential.

This error is popping up in some new unit tests for the xArchive PowerShell DSC resource in the [xPSDesiredStateConfiguration](https://github.com/PowerShell/xPSDesiredStateConfiguration) repository. I have provided a simplified reproduction of the problem in this issue, but the full test file we are running is available [here](https://github.com/kwirkykat/xPSDesiredStateConfiguration/blob/8eab199f91b4150b104077edccc2cbaefd7e1e8a/Tests/Unit/MSFT_xArchive.Tests.ps1#L1808) which is testing the code in [this file](https://github.com/kwirkykat/xPSDesiredStateConfiguration/blob/8eab199f91b4150b104077edccc2cbaefd7e1e8a/Tests/Unit/MSFT_xArchive.Tests.ps1), and you can see the full error throw we are seeing in AppVeyor [here](https://ci.appveyor.com/project/PowerShell/xpsdesiredstateconfiguration/build/6.0.781.0).

### Environment

Windows Server 2012 R2
WMF 5.0
Pester 4.0.2

### Code

```powershell
function Invoke-NewPSDrive {
    param ()

    $testUserName = 'TestUsername'
    $secureTestPassword = ConvertTo-SecureString -String 'F@kePassw0rd' -AsPlainText -Force

    $testCredential = New-Object -TypeName 'System.Management.Automation.PSCredential' -ArgumentList @( $testUsername, $secureTestPassword )

    $newPSDriveParameters = @{
        Name = [System.Guid]::NewGuid()
        PSProvider = 'FileSystem'
        Root = $env:temp
        Scope = 'Script'
        Credential = $testCredential
    }

    $psDrive = New-PSDrive @newPSDriveParameters
}

Describe 'Invoke-NewPSDrive Test' {
    $mockPSDrive = New-MockObject -Type 'System.Management.Automation.PSDriveInfo'
    Mock -CommandName 'New-PSDrive' -MockWith { return $mockPSDrive }

    It 'Should not throw' {
        { Invoke-NewPSDrive } | Should Not Throw
    }

    It 'Should call New-PSDrive mock' {
        Assert-MockCalled -CommandName 'New-PSDrive' -Exactly 1 -Scope 'Describe'
    }
}
```

## Error

The first It fails with: `Expected: the expression not to throw an exception. Message was {Cannot retrieve the dynamic parameters for the cmdlet. Exception calling "GetDynamicParameters" with "0" argument(s): "Dynamic parameters for NewDrive cannot be retrieved for the 'FileSystem' provider. The FileSystem provider supports credentials only on the New-PSDrive cmdlet. Perform the operation again without specifying credentials."}`

The full failure with the Pester output can be seen [here](https://ci.appveyor.com/project/KatieKeim/xpsdesiredstateconfiguration/build/6.0.233.0).

## Workaround

For now I will create a wrapper for New-PSDrive and mock that instead to hide the dynamic parameters.

**Comment by dlwyatt** [comment]
What's your full PSVersion number?  If it's 5.0.10586.122 or greater, it should be working fine.  (That's when Get-Command started returning dynamic parameter information; Pester takes advantage of this instead of using the older Reflection-based code.)

**Comment by kwirkykat** [comment]
@dlwyatt AppVeyor is running 5.0.10586.117 so then it should be fine once AppVeyor updates eventually. The workaround wrapper fixed it for now

**Comment by BenMcElroyUK** [comment]
This is still an issue on Windows 10 running version: 5.1.14393.1480

Simplified code to show the issue:

`Import-Module Pester
function Test-Something
{
    [System.Security.SecureString]$ADpasswd = ConvertTo-SecureString "password" -AsPlainText -Force
    [System.Management.Automation.PSCredential]$Cred = New-Object System.Management.Automation.PSCredential ("user", $ADpasswd)
    New-PSDrive 'Bla' -PSProvider FileSystem -Root '\\contoso.com' -Credential $Cred -Description 'Something'
}
Describe "Test-Something" {
    Context "What happens" {
        Mock New-PSDrive {}
        $result = Test-Something
    }
}
Invoke-Pester`

**Comment by it-praktyk** [comment]
I assume that the issue can be closed now. Feel free to reopen if you need more assistance.
